"""Aggregate per-baseline reports into a single CSV and emit the LaTeX
fragment for the new main-body tbl:comparison.
"""
from __future__ import annotations
# --- release path resolution ---
import os as _os
PSR_ROOT = _os.environ.get("PSR_ROOT") or _os.path.dirname(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
# Rasterized plan pages are NOT redistributed. Rebuild them from the public DOT
# PDFs (see README) and point PLANS_ROOT at the output directory.
PLANS_ROOT = _os.environ.get("PLANS_ROOT") or _os.path.join(PSR_ROOT, "data", "pages")
# --- end release path resolution ---

import json, os, glob, csv

REPORTS = f"{PSR_ROOT}/baselines_v2/reports"
OUT_CSV = f"{PSR_ROOT}/baselines_v2/reports/_aggregate.csv"
OUT_TEX = f"{PSR_ROOT}/baselines_v2/reports/_tbl_comparison.tex"

# Ordering and pretty names for the LaTeX table -- strong baselines on top,
# weak baselines below, ColPali (ours) at the bottom for emphasis.
ROW_ORDER = [
    # Strong modern visual retrievers (2025-2026 ViDoRe SOTA)
    ("nemotron_colembed_8b", "Nemotron-ColEmbed-8B \\citep{nvidia2026nemotroncolembed}", "Visual (Patch)", "Multi-vector late-int."),
    ("nemotron_colembed_4b", "Nemotron-ColEmbed-4B \\citep{nvidia2026nemotroncolembed}", "Visual (Patch)", "Multi-vector late-int."),
    ("colnomic_3b",         "ColNomic-3B \\citep{nomic2025colnomic}",     "Visual (Patch)",  "Multi-vector late-int."),
    ("colnomic_7b",         "ColNomic-7B \\citep{nomic2025colnomic}",     "Visual (Patch)",  "Multi-vector late-int."),
    ("colqwen25_v0_2",      "ColQwen2.5-v0.2 \\citep{faysse2025colpali}", "Visual (Patch)", "Multi-vector MaxSim"),
    ("colpali_v13",         "ColPali-v1.3 \\citep{faysse2025colpali}",    "Visual (Patch)",  "Multi-vector MaxSim"),
    ("dse_qwen2_2b",        "DSE-Qwen2-2B \\citep{ma2024dse}",            "Visual (Global)", "Single-vector dense"),
    ("visrag_ret",          "VisRAG-Ret \\citep{yu2024visrag}",           "Visual (Global)", "Single-vector dense"),
    ("bge_m3_ocr",          "BGE-M3 + OCR \\citep{chen2024bgem3}",        "Text (OCR)",      "Dense Vector"),
    # NV-Embed-v2 omitted: its released modeling code is incompatible with the
    # transformers version used here (rotary-embedding / cache API drift).
    # Weak (legacy)
    ("clip_vit_b32",        "CLIP ViT-B/32 \\citep{radford2021learning}", "Visual (Global)", "Global Embedding"),
    ("layoutlmv3",          "LayoutLMv3 \\citep{huang2022layoutlmv3}",    "Visual (Layout)", "Layout Embedding"),
    ("nougat_decode_minilm",     "Nougat-decode + MiniLM",                "OCR-free (Decode)", "Decode + Dense"),
    ("pix2struct_decode_minilm", "Pix2Struct-decode + MiniLM",            "OCR-free (Decode)", "Decode + Dense"),
    ("udop_decode_minilm",       "UDOP-decode + MiniLM",                  "OCR-free (Decode)", "Decode + Dense"),
    ("ocr_minilm",          "OCR + MiniLM",                               "Text (OCR)",      "Dense Vector"),
    ("visionrag_pyramid",   "VisionRAG (Pyramid, RRF)",                   "Hybrid (Text)",   "Structure-Aware RRF"),
    # Ours (loaded separately from the zero-shot eval_report.json if available)
    ("colpali_zeroshot",    "\\textbf{ColPali (Ours, zero-shot)}",        "Visual (Patch)",  "Multi-vector MaxSim"),
]


def load_reports():
    out = {}
    for path in glob.glob(os.path.join(REPORTS, "*.json")):
        name = os.path.splitext(os.path.basename(path))[0]
        if name.startswith("_") or name.startswith("latency"):
            continue
        try:
            out[name] = json.load(open(path))
        except Exception:
            continue
    # Pull ColPali zero-shot Recall@5 from the lora_finetune eval report if present.
    cp = f"{PSR_ROOT}/lora_finetune/eval_report.json"
    if os.path.exists(cp):
        try:
            r = json.load(open(cp))
            if "zeroshot" in r:
                out["colpali_zeroshot"] = {
                    "recall@5_overall": r["zeroshot"]["test_recall@5_overall"],
                    "n_test_queries": 424,
                    "n_index_pages": 1898,
                    "per_agency_recall@5": r["zeroshot"].get("test_per_agency", {}),
                }
        except Exception:
            pass
    return out


def main():
    reps = load_reports()
    # CSV
    fields = ["tag", "n_queries", "n_pages", "recall@5"]
    with open(OUT_CSV, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(fields)
        for tag in sorted(reps):
            r = reps[tag]
            w.writerow([tag, r.get("n_test_queries"), r.get("n_index_pages"),
                        f"{r.get('recall@5_overall', float('nan')):.2f}"])
    # LaTeX
    lines = []
    lines.append("% Auto-generated by baselines_v2/aggregate_reports.py")
    lines.append("\\begin{table*}[t]")
    lines.append("\\caption{Retrieval comparison on the 424-pair page-disjoint test split over the 1{,}898-page five-DOT index. Strong (modern) baselines on top, legacy/weak baselines below, our zero-shot ColPali at the bottom. All numbers measured under an identical evaluation protocol; per-agency and per-category bootstrap CIs are reported in Appendix~\\ref{app:bench-stats}.}\\label{tbl:comparison}")
    lines.append("\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}llllc@{}}")
    lines.append("\\toprule")
    lines.append("Method & Modality & Mechanism & $N_{\\text{idx}}$ & Recall@5 \\\\")
    lines.append("\\midrule")
    lines.append("\\multicolumn{5}{l}{\\emph{Strong modern baselines (2024--2025)}} \\\\")
    section_strong = True
    for tag, pretty, mod, mech in ROW_ORDER:
        if tag == "clip_vit_b32" and section_strong:
            lines.append("\\midrule")
            lines.append("\\multicolumn{5}{l}{\\emph{Legacy baselines (kept for transparency)}} \\\\")
            section_strong = False
        if tag == "colpali_zeroshot":
            lines.append("\\midrule")
        r = reps.get(tag)
        score = f"{r['recall@5_overall']:.2f}\\%" if r else "---"
        n_idx = r.get("n_index_pages", "---") if r else "---"
        lines.append(f"{pretty} & {mod} & {mech} & {n_idx} & {score} \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular*}")
    lines.append("\\end{table*}")
    with open(OUT_TEX, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[done] -> {OUT_CSV}")
    print(f"[done] -> {OUT_TEX}")


if __name__ == "__main__":
    main()
