"""Bootstrap 95% percentile-CIs on Recall@5 over the 424-pair test split.

Reads the per-baseline hit-vectors saved by every script in baselines_v2/
(via _eval_lib.save_report). For each baseline and each agency it resamples
the hit vector with replacement N=10,000 times (seed 42) and reports the
[2.5%, 97.5%] percentile interval. Emits a LaTeX fragment that replaces
`tbl:bench-stats-primary` in Appendix B.
"""
from __future__ import annotations
# --- release path resolution ---
import os as _os
PSR_ROOT = _os.environ.get("PSR_ROOT") or _os.path.dirname(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
# Rasterized plan pages are NOT redistributed. Rebuild them from the public DOT
# PDFs (see README) and point PLANS_ROOT at the output directory.
PLANS_ROOT = _os.environ.get("PLANS_ROOT") or _os.path.join(PSR_ROOT, "data", "pages")
# --- end release path resolution ---

import json, os, glob
import numpy as np

REPORTS = f"{PSR_ROOT}/baselines_v2/reports"
OUT_JSON = os.path.join(REPORTS, "_bootstrap_cis_424.json")
OUT_TEX = os.path.join(REPORTS, "_tbl_bootstrap_cis.tex")

N_BOOT = 10000
SEED = 42

# Same ordering as aggregate_reports.ROW_ORDER
ROW_ORDER = [
    ("colqwen25_v0_2",            "ColQwen2.5-v0.2"),
    ("dse_qwen2_2b",              "DSE-Qwen2-2B"),
    ("visrag_ret",                "VisRAG-Ret"),
    ("bge_m3_ocr",                "BGE-M3 + OCR"),
    ("clip_vit_b32",              "CLIP ViT-B/32"),
    ("layoutlmv3",                "LayoutLMv3"),
    ("nougat_decode_minilm",      "Nougat-decode + MiniLM"),
    ("pix2struct_decode_minilm",  "Pix2Struct-decode + MiniLM"),
    ("udop_decode_minilm",        "UDOP-decode + MiniLM"),
    ("ocr_minilm",                "OCR + MiniLM"),
    ("visionrag_pyramid",         "VisionRAG (Pyramid, RRF)"),
    ("hpc_colpali_bq",            "HPC-ColPali (BQ)"),
]


def bootstrap_recall(hits, n_boot=N_BOOT, seed=SEED):
    rng = np.random.default_rng(seed)
    h = np.asarray(hits, dtype=np.float32)
    if h.size == 0:
        return float("nan"), float("nan"), float("nan")
    idx = rng.integers(0, h.size, size=(n_boot, h.size))
    samples = h[idx].mean(axis=1) * 100.0
    return float(h.mean() * 100.0), float(np.percentile(samples, 2.5)), float(np.percentile(samples, 97.5))


def load_report(tag):
    p = os.path.join(REPORTS, f"{tag}.json")
    if not os.path.exists(p): return None
    try:
        return json.load(open(p))
    except Exception:
        return None


def main():
    rows = []
    for tag, pretty in ROW_ORDER:
        r = load_report(tag)
        if r is None: continue
        hits = r.get("hits") or []
        if not hits: continue
        # Per-agency hits: rebuild from test set
        test = [json.loads(l) for l in open(f"{PSR_ROOT}/lora_finetune/split_test.jsonl")]
        by_agency = {}
        for h, q in zip(hits, test):
            by_agency.setdefault(q["agency"], []).append(h)
        # Overall
        pt, lo, hi = bootstrap_recall(hits)
        agencies = {}
        for a, hl in sorted(by_agency.items()):
            pa, la, ha = bootstrap_recall(hl)
            agencies[a] = {"n": len(hl), "point": pa, "lo": la, "hi": ha}
        rows.append({
            "tag": tag, "pretty": pretty,
            "n": len(hits), "point": pt, "lo": lo, "hi": hi,
            "per_agency": agencies,
        })

    # Append ColPali zero-shot from lora_finetune/eval_report.json if test_hits saved
    cp_path = f"{PSR_ROOT}/lora_finetune/eval_report.json"
    if os.path.exists(cp_path):
        cp = json.load(open(cp_path))
        cp_hits = cp.get("zeroshot", {}).get("test_hits_at_5")
        if cp_hits:
            pt, lo, hi = bootstrap_recall(cp_hits)
            rows.append({
                "tag": "colpali_zeroshot", "pretty": "\\textbf{ColPali (Ours, zero-shot)}",
                "n": len(cp_hits), "point": pt, "lo": lo, "hi": hi,
                "per_agency": {},
            })

    with open(OUT_JSON, "w") as f:
        json.dump(rows, f, indent=2)

    # ---- LaTeX --------------------------------------------------------------
    lines = []
    lines.append("% Auto-generated by baselines_v2/bootstrap_cis_424.py")
    lines.append("\\begin{table*}[!t]")
    lines.append("\\caption{Per-baseline Recall@5 with 95\\% bootstrap CIs on the 424-pair page-disjoint test split (10{,}000 resamples, seed 42). Per-agency $N$: WYDOT $=53$, Caltrans $=134$, AZDOT $=46$, CDOT $=31$, FDOT $=160$.}\\label{tbl:bench-stats-retrieval}")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular*}{\\textwidth}{@{\\extracolsep{\\fill}}lcccccc@{}}")
    lines.append("\\toprule")
    lines.append("Method & Overall (\\%) & WYDOT & Caltrans & AZDOT & CDOT & FDOT \\\\")
    lines.append("\\midrule")
    agencies_order = ["WYDOT", "Caltrans", "AZDOT", "CDOT", "FDOT"]
    for row in rows:
        cells = [row["pretty"], f"{row['point']:.2f} [{row['lo']:.1f}, {row['hi']:.1f}]"]
        for ag in agencies_order:
            a = row["per_agency"].get(ag)
            if a:
                cells.append(f"{a['point']:.1f} [{a['lo']:.1f}, {a['hi']:.1f}]")
            else:
                cells.append("---")
        lines.append(" & ".join(cells) + " \\\\")
    lines.append("\\bottomrule")
    lines.append("\\end{tabular*}")
    lines.append("\\end{table*}")
    with open(OUT_TEX, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[done] -> {OUT_JSON}")
    print(f"[done] -> {OUT_TEX}")


if __name__ == "__main__":
    main()
